---
title: "NI Postcode and Crime Data"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---
This document describes the methods used during and results obtained from analysis of postcode and crime data for Northern Ireland. The postcode dataset is the focus of the first section, while the next section features the steps taken in analysing the crime dataset.

# NI Postcode Data
a) Show the Total number of rows, the structure of the data frame, and first 10 rows of the data frame containing all of the NI Postcode data.

b) Add a suitable title for each attribute of the data.


c) Remove or replace missing entries with a suitable identifier. [Decide whether it is best to remove missing data or to recode it. Discuss missing data and justify your decision in detail.]

## iv.
Task: Show the total number of missing values for each column in the postcode data frame.

## v.
Task: Move the primary key identifier to the start of the dataset.

## vi.
Task: Create a new dataset called Limavady_data. Store within it only information where locality, townland and town contain the name Limavady. Count and display the number of rows. Store this information in a csv file called Limavady.

## vii.
Task: Save the modified NIPostcode dataset in a csv file called CleanNIPostcodeData.

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.



When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

# NI Crime Data
## i.

## ii.

## iii.

## iv.

## v.

## vi.

## vii.

## viii.

## ix.

## x.

## xi.

## xii.